@startuml Diagrama de classe Aluguel de Carros
scale 2
left to right direction

skinparam ClassAttributeFontSize 0
class Cliente{
-String login
-String senha

}

Class Agente{

}

Class Contratante{

}


@enduml