@startuml Diagrama
skinparam classAttributeIconSize 0

Usuario <|.. Agente
Usuario <|.. Cliente
Aluguel "1" *-- "1" Contrato : contém
Aluguel "1" -- "1" Cliente : contém
Aluguel "1" o-- "1" Automovel : contém
Aluguel "*" o-- "1" Agente : contém
Cliente "*" --o "3" Empregador : emprega
TipoAgente <|-- Agente

interface Usuario {
    -id : Long
    -login: String
    -senha: String
    +login() : void
    +logout() : void
    +registrar() : Boolean
}

class Cliente {
    -rg : String
    -cpf : String
    -nome : String
    -endereco : String
    -profissao : String
    -entidadeEmpregadora : String
    -rendimentosAuferidos : Double[3]
    +solicitarAluguel() : void
    +editarPedidoAluguel() : void
    +visualizarPedidoAluguel() : Aluguel
    +excluirPedidoAluguel() : void
}

class Agente {
    -cnpj : String
    -tipo : TipoAgente
    +analisarPedidoAluguel() : Boolean
    +modificarPedidoAluguel() : Boolean
}

enum TipoAgente{
    BANCO,
    EMPRESA
}

class Empregador {
    -id: Long
    -cpnj : String
    -nome : String
}

class Aluguel {
    -id : Long
    -aprovado : Boolean
    -agente : Agente
    -cliente : Cliente
    -automovel : Automovel
    -contrato : Contrato
}

class Contrato {
    -id : Long
}

class Automovel {
    -id : Long
    -matricula : String
    -ano : String
    -marca : String
    -modelo : String
    -placa : String
    -proprietario : User
}

@enduml